// examples/vue/src/App.vue
<template>
  <div id="app">
    <h1>Hello MDX</h1>
    <MDXProvider v-bind:components="components">
      <Test />
    </MDXProvider>
  </div>
</template>

<script>
import {MDXProvider} from '@mdx-js/vue'
import HelloWorld from './components/HelloWorld'
import Test from './test.mdx'

export default {
  name: 'app',
  components: {
    Test,
    MDXProvider
  },
  data() {
    return {
      components: {
        section: props => HelloWorld,
        wrapper: props => 'article'
      }
    }
  }
}
</script>

// examples/create-react-app/src/App.js
import React, {Component} from 'react'
import {MDXProvider} from '@mdx-js/tag'

import Hello from './hello.md'

const components = {
  h1: props => <h1 style={{color: 'tomato'}} {...props} />
}

class App extends Component {
  render() {
    return (
      <MDXProvider components={components}>
        <Hello />
      </MDXProvider>
    )
  }
}

export default App
